In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("titanic.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [2]:
y = df["Survived"]
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]]

print("X:")
display(X.head())

print("y:")
display(y.head())

X:


,Pclass,Age,Sex,Fare,SibSp,Parch
0,3,22.0,male,7.2500,1,0
1,1,38.0,female,71.2833,1,0
2,3,26.0,female,7.9250,0,0
3,1,35.0,female,53.1000,1,0
4,3,35.0,male,8.0500,0,0


y:


0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [3]:
print("Пропущенные значения:")
print(X.isnull().sum())

Пропущенные значения:
Pclass      0
Age       177
Sex         0
Fare        0
SibSp       0
Parch       0
dtype: int64


In [4]:
X["Age"] = X["Age"].fillna(X["Age"].median())

print("Пропуски после обработки Age:")
print(X.isnull().sum())

Пропуски после обработки Age:
Pclass    0
Age       0
Sex       0
Fare      0
SibSp     0
Parch     0
dtype: int64


/tmp/ipykernel_1116/2136265842.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Age"] = X["Age"].fillna(X["Age"].median())


In [5]:
X["Sex"] = X["Sex"].map({
    "male": 0,
    "female": 1
})

print("Подготовленные признаки:")
display(X.head())

Подготовленные признаки:


/tmp/ipykernel_1116/3461458744.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = X["Sex"].map({


,Pclass,Age,Sex,Fare,SibSp,Parch
0,3,22.0,0,7.2500,1,0
1,1,38.0,1,71.2833,1,0
2,3,26.0,1,7.9250,0,0
3,1,35.0,1,53.1000,1,0
4,3,35.0,0,8.0500,0,0


In [6]:
print("Информация о X:")
X.info()

print("\nПропуски:")
print(X.isnull().sum())

Информация о X:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Age     891 non-null    float64
 2   Sex     891 non-null    int64  
 3   Fare    891 non-null    float64
 4   SibSp   891 non-null    int64  
 5   Parch   891 non-null    int64  
dtypes: float64(2), int64(4)
memory usage: 41.9 KB

Пропуски:
Pclass    0
Age       0
Sex       0
Fare      0
SibSp     0
Parch     0
dtype: int64


In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 6)
X_test: (179, 6)
y_train: (712,)
y_test: (179,)


In [8]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled:")
print(X_train_scaled[:5])

print("\nX_test_scaled:")
print(X_test_scaled[:5])

X_train_scaled:
[[-1.61413602  1.25364106 -0.7243102  -0.07868358 -0.47072241 -0.47934164]
 [-0.40055118 -0.47728355 -0.7243102  -0.37714494 -0.47072241 -0.47934164]
 [ 0.81303367  0.21508629 -0.7243102  -0.47486697 -0.47072241 -0.47934164]
 [ 0.81303367 -0.24649361 -0.7243102  -0.47623026  0.37992316 -0.47934164]
 [ 0.81303367 -1.78509326  1.38062393 -0.02524937  2.93185988  2.04874166]]

X_test_scaled:
[[ 0.81303367 -0.09263364 -0.7243102  -0.33390078  0.37992316  0.78470001]
 [-0.40055118  0.13815631 -0.7243102  -0.42528387 -0.47072241 -0.47934164]
 [ 0.81303367 -0.7080735  -0.7243102  -0.47486697 -0.47072241 -0.47934164]
 [-0.40055118 -1.78509326  1.38062393  0.00796649 -0.47072241  0.78470001]
 [ 0.81303367 -1.1696534   1.38062393 -0.41100201  0.37992316 -0.47934164]]


In [9]:
print("Размер X_train:", X_train.shape)
print("Размер X_test:", X_test.shape)
print("Размер y_train:", y_train.shape)
print("Размер y_test:", y_test.shape)
print("Размер X_train_scaled:", X_train_scaled.shape)
print("Размер X_test_scaled:", X_test_scaled.shape)

print("\nГотово: данные очищены, Sex преобразован в числа,")
print("выборки разделены в соотношении 80/20 и выполнено масштабирование.")

Размер X_train: (712, 6)
Размер X_test: (179, 6)
Размер y_train: (712,)
Размер y_test: (179,)
Размер X_train_scaled: (712, 6)
Размер X_test_scaled: (179, 6)

Готово: данные очищены, Sex преобразован в числа,
выборки разделены в соотношении 80/20 и выполнено масштабирование.
